export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const ADD_SHIPPING_INFO = "ADD_SHIPPING_INFO"

export const CART_ITEMS_REQUEST = "CART_ITEMS_REQUEST"
export const CART_ITEMS_SUCCESS = "CART_ITEMS_SUCCESS"
export const CART_ITEMS_FAIL = "CART_ITEMS_FAIL"
export const CART_ITEMS_CLEAR = "CART_ITEMS_CLEAR"
export const CART_ITEMS_CLEAR_ERRORS = "CART_ITEMS_CLEAR_ERRORS"
export const CART_ITEMS_UPDATE_QUANTITY = "CART_ITEMS_UPDATE_QUANTITY"

export const CLEAR_CART = "CLEAR_CART"
